- name: Configure frontend (Amazon Linux)
  hosts: frontend
  become: true
  tasks:
    - name: Disable SELinux
      selinux:
        state: disabled

    - name: Disable firewalld
      service:
        name: firewalld
        state: stopped
        enabled: no

    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Configure nginx for reverse proxy
      copy:
        dest: /etc/nginx/conf.d/proxy.conf
        content: |
          server {
              listen 80;
              location / {
                  proxy_pass http://{{ hostvars['u21.local'].ansible_host }}:19999/;
              }
          }

    - name: Start and enable nginx
      service:
        name: nginx
        state: started
        enabled: yes
