- name: Configure backend (Ubuntu)
  hosts: backend
  become: true
  tasks:
    - name: Disable SELinux (Ubuntu doesn't use it, so skip)
      command: echo "SELinux not applicable on Ubuntu"
      changed_when: false

    - name: Disable firewalld
      apt:
        name: ufw
        state: absent

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Netdata
      apt:
        name: netdata
        state: present

    - name: Ensure Netdata is running
      service:
        name: netdata
        state: started
        enabled: yes
